name: BlazeDemo
on: [push]
jobs:
  BlazeDemo-cypress-chrome-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:run:chrome
  BlazeDemo-cypress-firefox-run:
     runs-on: windows-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Cypress.io
         uses: cypress-io/github-action@v6
         with:
           start: npm run cypress:run:firefox
  BlazeDemo-cypress-edge-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:run:edge
       
      
